# Generated by Django 3.0.6 on 2020-05-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salvado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Salvados',
            },
        ),
    ]
